### ISSUE TITLE
Output picture size

### ISSUE THREAD

**Issue by amcaw** [g4me-time/Himawari-8-Timelapse-Script#4]
Awesome projet ! How would you do to change output picture size. I would like higher resolution than 550x550. Could you please show us how to change the files size ?

**Comment by timkalkus** [comment]
Select an other tile size that 1x1 (20x20 is the highest for RGB) and hold left click while dragging over the image to select a region.
Depending on how many tiles you have selected, you will get a higher resolution (the more tiles, the higher the total resolution).
I hope this explanation did clear things up. Maybe I will make a small tutorial about all the different functionality, but I am not sure when I would have time for that :)

**Comment by amcaw** [comment]
How, that's exactly what I wanted ! Thank you so much
